
package com.gft.starters.g2.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculadora", targetNamespace = "http://service.g2.starters.gft.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculadora {


    /**
     * 
     * @param operador2
     * @param operador1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "divisionReturn", targetNamespace = "http://service.g2.starters.gft.com")
    @RequestWrapper(localName = "division", targetNamespace = "http://service.g2.starters.gft.com", className = "com.gft.starters.g2.service.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://service.g2.starters.gft.com", className = "com.gft.starters.g2.service.DivisionResponse")
    public double division(
        @WebParam(name = "operador1", targetNamespace = "http://service.g2.starters.gft.com")
        double operador1,
        @WebParam(name = "operador2", targetNamespace = "http://service.g2.starters.gft.com")
        double operador2);

    /**
     * 
     * @param operador2
     * @param operador1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "restaReturn", targetNamespace = "http://service.g2.starters.gft.com")
    @RequestWrapper(localName = "resta", targetNamespace = "http://service.g2.starters.gft.com", className = "com.gft.starters.g2.service.Resta")
    @ResponseWrapper(localName = "restaResponse", targetNamespace = "http://service.g2.starters.gft.com", className = "com.gft.starters.g2.service.RestaResponse")
    public double resta(
        @WebParam(name = "operador1", targetNamespace = "http://service.g2.starters.gft.com")
        double operador1,
        @WebParam(name = "operador2", targetNamespace = "http://service.g2.starters.gft.com")
        double operador2);

    /**
     * 
     * @param operador2
     * @param operador1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "multiplicacionReturn", targetNamespace = "http://service.g2.starters.gft.com")
    @RequestWrapper(localName = "multiplicacion", targetNamespace = "http://service.g2.starters.gft.com", className = "com.gft.starters.g2.service.Multiplicacion")
    @ResponseWrapper(localName = "multiplicacionResponse", targetNamespace = "http://service.g2.starters.gft.com", className = "com.gft.starters.g2.service.MultiplicacionResponse")
    public double multiplicacion(
        @WebParam(name = "operador1", targetNamespace = "http://service.g2.starters.gft.com")
        double operador1,
        @WebParam(name = "operador2", targetNamespace = "http://service.g2.starters.gft.com")
        double operador2);

    /**
     * 
     * @param operador2
     * @param operador1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "sumaReturn", targetNamespace = "http://service.g2.starters.gft.com")
    @RequestWrapper(localName = "suma", targetNamespace = "http://service.g2.starters.gft.com", className = "com.gft.starters.g2.service.Suma")
    @ResponseWrapper(localName = "sumaResponse", targetNamespace = "http://service.g2.starters.gft.com", className = "com.gft.starters.g2.service.SumaResponse")
    public double suma(
        @WebParam(name = "operador1", targetNamespace = "http://service.g2.starters.gft.com")
        double operador1,
        @WebParam(name = "operador2", targetNamespace = "http://service.g2.starters.gft.com")
        double operador2);

}
